Description: >
  This template contains following security groups:
   - ECS Cluster hosts
   - Load Balancer
  
Parameters:
  EnvironmentName:
    Description: The name of the environemt. It will be prefixed to a resource names
    Type: String
    Default: dev
 
  VPCStackTemplateURL:
    Description: The location of file containing the template body.
    Type: String
  
  SecurityGroupStackTemplateURL:
    Description: The location of file containing the template body.
    Type: String
  LoadBalancerStackTemplateURL:
    Description: The location of file containing the template body.
    Type: String
  IAMRolesStackTemplateURL:
    Description: The location of file containing the template body.
    Type: String
  ECSClusterStackTemplateURL:
    Description: The location of file containing the template body.
    Type: String

  InstanceType:
    Type: String
    Default: t2.small
    Description: Class of EC2 instance used to host containers.
    AllowedValues: 
      - t2.micro
      - t2.small
  DesiredCapacity:
    Type: Number
    Default: '1'
    Description: Number of EC2 instances to launch in your ECS cluster.
  MinSize:
    Type: Number
    Default: '1'
    Description: Minimum number of EC2 instances that can be launched in your ECS cluster.
  MaxSize:
    Type: Number
    Default: '1'
    Description: Maximum number of EC2 instances that can be launched in your ECS cluster.
  ECSAMI:
    Description: The Amazon Machine Image ID used for the cluster
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref VPCStackTemplateURL
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref SecurityGroupStackTemplateURL
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ECSClusterVPC: !GetAtt VPC.Outputs.ClusterVPC

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref LoadBalancerStackTemplateURL
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ECSClusterVPC: !GetAtt VPC.Outputs.ClusterVPC
        ECSLoadBalancerSecurityGroup: !GetAtt SecurityGroups.Outputs.ECSLoadBalancerSecurityGroup
        ECSClusterVPCPublicSubnets: !GetAtt VPC.Outputs.PublicSubnets

  IAMRoles:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref IAMRolesStackTemplateURL
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  ECSCluster:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref ECSClusterStackTemplateURL
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        DesiredCapacity: !Ref DesiredCapacity
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        ECSAMI: !Ref ECSAMI
        ECSClusterVPCPrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
        ECSClusterSecurityGroup: !GetAtt SecurityGroups.Outputs.ECSClusterSecurityGroup
        ECSClusterIAMRole: !GetAtt IAMRoles.Outputs.ECSClusterIAMRole


  
# Outputs:
#   ECSClusterSecurityGroup:
#     Description: A reference to the security group for ECS hosts
#     Value: !Ref ECSClusterSecurityGroup
#     Export: 
#       Name: ECSClusterSecurityGroup

#   ECSLoadBalancerSecurityGroup:
#     Description: A reference to the security group for load balancers
#     Value: !Ref ECSLoadBalancerSecurityGroup
#     Export: 
#       Name: ECSLoadBalancerSecurityGroup